import type { Platform, SourceInput } from "./research-sources";

// Public projection reviewed at absolutepraya/bursawatch f36823f.
// Tests check a pinned public fixture, not private backend files or live state.
// Never import watcher config here: it also contains private delivery identifiers.
// Biographical descriptions are paraphrased from public profiles, not credential verification.
export const recommendedSources = [
  {
    id: "kutekians",
    name: "Almer Sad",
    handle: "@Kutekians",
    url: "https://x.com/kutekians",
    image: "/sources/kutekians.png",
    portrait: true,
    platform: "x",
    background: "His public profile describes work in M&A and private capital.",
    coverage: "Macro and investment commentary.",
    reason: "A focused starting point for broad market context.",
    evidence: "https://x.com/Kutekians",
    label: "Team selection",
    topics: ["macro_news"],
  },
  {
    id: "rickyho1989",
    name: "Ricky Ho",
    handle: "@rickyho_1989",
    url: "https://x.com/rickyho_1989",
    image: "/sources/rickyho_1989.png",
    portrait: true,
    platform: "x",
    background:
      "His public profile describes public-market portfolio management and equity research.",
    coverage: "Global equities and market commentary.",
    reason: "Connect company developments with the wider market.",
    evidence: "https://x.com/rickyho_1989",
    label: "Team selection",
    topics: ["macro_news", "id_stocks_news", "us_stocks_news"],
  },
  {
    id: "writingtorch",
    name: "Torch",
    handle: "@writingtorch",
    url: "https://x.com/writingtorch",
    image: "/sources/writingtorch.png",
    portrait: true,
    platform: "x",
    background: "Publishes summaries tagged RangkumReport and RangkumKeterbukaanInformasi.",
    coverage: "IDX company reports and disclosures.",
    reason: "Follow company disclosures through a research-focused account.",
    evidence: "https://x.com/writingtorch",
    label: "Team selection",
    topics: ["macro_news", "id_stocks_news"],
  },
  {
    id: "arvinhonami",
    name: "Arvin Honami",
    handle: "@ArvinHonami",
    url: "https://x.com/arvinhonami",
    image: "/sources/arvinhonami.png",
    portrait: true,
    platform: "x",
    background: "His public profile emphasizes data-led investing.",
    coverage: "Indonesian investing and market research.",
    reason: "Add an individual research perspective to your company watch.",
    evidence: "https://x.com/ArvinHonami",
    label: "Team selection",
    topics: ["macro_news", "id_stocks_news", "us_stocks_news"],
  },
  {
    id: "doktermarket",
    name: "DokterMarket",
    handle: "@doktermarket",
    url: "https://x.com/doktermarket",
    image: "/sources/doktermarket.png",
    portrait: true,
    platform: "x",
    background: "A trading account whose profile describes a technical approach to IDX markets.",
    coverage: "Technical research and market timing.",
    reason: "Follow published setups with their original source attached.",
    evidence: "https://x.com/doktermarket",
    label: "Team selection",
    topics: ["macro_news", "id_stocks_news", "id_stocks_swing"],
  },
  {
    id: "txthariansaham",
    name: "Ga Cuan Ga tidur",
    handle: "@txthariansaham",
    url: "https://x.com/txthariansaham",
    image: "/sources/txthariansaham.png",
    portrait: true,
    platform: "x",
    background: "A personal trading account included in the team’s current watchlist.",
    coverage: "IDX trading commentary.",
    reason: "Keep its market posts while choosing the topics relevant to you.",
    evidence: "https://x.com/txthariansaham",
    label: "Team selection",
    topics: ["macro_news", "id_stocks_news", "id_stocks_swing"],
  },
  {
    id: "wavetiga",
    name: "Andriy",
    handle: "@wavetiga",
    url: "https://x.com/wavetiga",
    image: "/sources/wavetiga.png",
    portrait: true,
    platform: "x",
    background: "His public profile describes trading on the Indonesia Stock Exchange.",
    coverage: "Elliott wave and technical analysis.",
    reason: "Add a technical view alongside company and macro research.",
    evidence: "https://x.com/wavetiga",
    label: "Team selection",
    topics: ["macro_news", "id_stocks_news", "id_stocks_swing", "us_stocks_news"],
  },
  {
    id: "aldotjahjadi8",
    name: "IHSG Journal",
    handle: "@aldotjahjadi8",
    url: "https://x.com/aldotjahjadi8",
    image: "/sources/aldotjahjadi8.png",
    portrait: true,
    platform: "x",
    background: "Included in the team’s watchlist for macro and IDX company news.",
    coverage: "IHSG and broad-market commentary.",
    reason: "Follow the market-level context around your stock watch.",
    evidence: "https://x.com/aldotjahjadi8",
    label: "Team selection",
    topics: ["macro_news", "id_stocks_news"],
  },
  {
    id: "kobeissiletter",
    name: "The Kobeissi Letter",
    handle: "@KobeissiLetter",
    url: "https://x.com/kobeissiletter",
    image: "/sources/kobeissiletter.png",
    portrait: true,
    platform: "x",
    background: "A publication focused on the global capital markets.",
    coverage: "Global capital-market commentary.",
    reason: "Add international context to domestic market developments.",
    evidence: "https://x.com/KobeissiLetter",
    label: "Team selection",
    topics: ["macro_news", "us_stocks_news"],
  },
  {
    id: "bri-danareksa-sekuritas",
    name: "BRI Danareksa Sekuritas",
    handle: "BRIDS Research",
    url: "https://www.whatsapp.com/channel/0029VbAjdnb60eBhwVdJxj1c",
    image: "/brokers/brids-logo.png",
    portrait: false,
    platform: "whatsapp",
    background: "Brokerage research from BRI Danareksa.",
    coverage: "Company news, macro commentary and tagged technical reviews.",
    reason: "The brokerage channel already included in the team’s setup.",
    evidence: "https://www.whatsapp.com/channel/0029VbAjdnb60eBhwVdJxj1c",
    label: "Team selection",
    topics: ["macro_news", "id_stocks_news", "id_stocks_swing"],
  },
  {
    id: "insidertracker",
    name: "Insider Tracker",
    handle: "@InsiderTrackX",
    url: "https://x.com/insidertrackx",
    image: "",
    portrait: false,
    platform: "x",
    background: "An account in the team’s reviewed source configuration.",
    coverage: "Company news and broader market developments.",
    reason: "Read its original posts alongside source-grounded summaries.",
    evidence: "https://x.com/InsiderTrackX",
    label: "Team selection",
    topics: ["macro_news", "id_stocks_news", "us_stocks_news"],
  },
  ...[
    ["beyondthefundamental", "beyondthefundamental", "Beyond thy Fundamental"],
    ["investart_id", "investart_id", "Investart"],
    ["avenirresearch_id", "avenirresearch.id", "Avenir Research"],
    ["acresresearch", "acresresearch", "Acres Research"],
    ["sectorsapp", "sectorsapp", "Sectors"],
    ["cukhurukuque", "cukhurukuque", "Cukhurukuque"],
    ["notintofinance", "notintofinance", "NIFI"],
  ].map(([id, handle, name]) => ({
    id,
    name,
    handle: `@${handle}`,
    url: `https://www.instagram.com/${handle}`,
    image: "",
    portrait: false,
    platform: "instagram" as const,
    background: "An Instagram account in the team’s reviewed source configuration.",
    coverage: "Company research and macro context on Instagram.",
    reason: "Read public posts and reels with their source context preserved.",
    evidence: `https://www.instagram.com/${handle}`,
    label: "Team selection",
    topics: ["macro_news", "id_stocks_news"] as SourceInput["topics"],
  })),
  {
    id: "bank-indonesia",
    name: "Bank Indonesia",
    handle: "@bank_indonesia",
    url: "https://x.com/bank_indonesia",
    image: "/sources/bank-indonesia.png",
    portrait: false,
    platform: "x",
    background: "Indonesia’s central bank.",
    coverage: "Monetary policy, the rupiah and economic developments.",
    reason: "Follow policy announcements at their source.",
    evidence: "https://www.bi.go.id/en/layanan/kas-bi/default.aspx",
    label: "Official institution",
    topics: ["macro_news"],
  },
  {
    id: "ojk",
    name: "Otoritas Jasa Keuangan",
    handle: "@ojkindonesia",
    url: "https://x.com/ojkindonesia",
    image: "/sources/ojk.png",
    portrait: false,
    platform: "x",
    background: "Indonesia’s financial services authority.",
    coverage: "Financial regulation, supervision and consumer protection.",
    reason: "Keep regulatory announcements alongside market research.",
    evidence:
      "https://ojk.go.id/en/berita-dan-kegiatan/publikasi/Pages/OJK-Services-and-Information-Quick-Access.aspx",
    label: "Official institution",
    topics: ["macro_news"],
  },
] satisfies {
  id: string;
  name: string;
  handle: string;
  url: string;
  image: string;
  portrait: boolean;
  platform: Platform;
  background: string;
  coverage: string;
  reason: string;
  evidence: string;
  label: string;
  topics: SourceInput["topics"];
}[];
