#!/usr/bin/env python3
"""Write the SFX layer into index.html between the SFX markers.

Each event is (visual hit time in film seconds, sound, volume). The sound's
measured peak offset is subtracted so its loudest moment lands on the hit.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PEAK = {"whoosh-short": 0.16, "whoosh": 0.16, "click": 0.07, "click-soft": 0.07, "key-press": 0.07,
        "pop": 0.11, "ping": 0.32, "impact-bass-1": 0.07, "impact-bass-2": 0.36, "sparkle": 0.02}
DUR = {"whoosh-short": 0.57, "whoosh": 0.57, "click": 0.37, "click-soft": 0.37, "key-press": 0.4,
       "pop": 0.72, "ping": 1.32, "impact-bass-1": 2.1, "impact-bass-2": 2.59, "sparkle": 1.8}

E = []
# s1: hook words, pain cards (2.0s each on the grid), heroes, emphasis
for t in [0.24, 0.35, 0.47, 0.61, 0.73, 0.9, 1.02, 1.4, 1.51, 1.64]:
    E.append((t + 0.04, "key-press", 0.16))
for i, t0 in enumerate([2.23, 4.23, 6.23, 8.23]):
    E.append((t0 + 0.08, "whoosh-short", 0.42))
    E.append((t0 + 0.52, "impact-bass-1" if i == 3 else "pop", 0.5 if i == 3 else 0.3))
E += [(3.3, "pop", 0.26)]                      # KETR chip
E += [(5.25, "key-press", 0.3), (5.45, "key-press", 0.25)]  # money ticking
E += [(6.6, "whoosh", 0.22)]                   # kelas pan to Diamond
E += [(8.6, "whoosh-short", 0.3)]              # TRUE candles crash in
# s2 (starts 10.23): wall, marker, absorb, drop
E += [(10.3, "whoosh", 0.32), (10.9, "whoosh-short", 0.22), (11.72, "sparkle", 0.12)]
E += [(14.85, "whoosh-short", 0.22), (14.99, "whoosh-short", 0.2), (15.13, "whoosh-short", 0.2)]
E += [(16.22, "impact-bass-2", 0.55)]
E += [(19.6, "whoosh", 0.3)]
# s3: hub pop, chips, dive, pings
E.append((19.78, "pop", 0.38))
for i in range(5):
    E.append((20.23 + 0.25 * i + 0.06, "pop", 0.28))
# "Enriched by Sectors" tab drops under each pill
for i in range(5):
    E.append((19.73 + 1.9 + i * 0.17 + 0.12, "click-soft", 0.24))
E.append((23.12, "whoosh", 0.35))
for i in range(3):
    E.append((23.48 + 0.5 * i + 0.08, "ping", 0.3))
    E.append((24.19 + 0.5 * i, "click-soft", 0.2))  # Sectors card resolves
# s4: open, scroll, search keys, click, thread, punch
E += [(26.08, "whoosh-short", 0.28), (26.5, "whoosh", 0.25)]
for i in range(4):
    E.append((28.86 + 0.12 * i, "key-press", 0.45))
E += [(30.55, "click", 0.55), (30.8, "whoosh-short", 0.28), (32.26, "impact-bass-1", 0.42)]
# s5 (34.27): open, phase morphs (2.5 / 2.0 / 2.5 / 3.0s), verdict
E += [(34.1, "whoosh-short", 0.28)]
E += [(36.81, "whoosh-short", 0.18), (38.81, "whoosh-short", 0.18), (41.31, "whoosh-short", 0.18)]
E += [(36.77 + 0.62, "click-soft", 0.22), (38.77 + 0.62, "click-soft", 0.22), (41.27 + 0.62, "click-soft", 0.22)]  # Sectors badges
E += [(42.79, "key-press", 0.4), (43.05, "key-press", 0.4), (43.29, "pop", 0.4)]
# s6 (44.29): one click and one stamp per quadrant, then the "lainnya" pill
for q in [44.29, 45.79, 47.29, 48.79]:
    E.append((q + 0.5, "click", 0.5))
    E.append((q + 1.02, "impact-bass-1", 0.36))
E += [(44.1, "whoosh-short", 0.25), (50.1, "pop", 0.35), (52.1, "whoosh-short", 0.25)]
# s7 (52.33): gains cards dealt, payoff line, cards gather, the mark on the last kick
for o in range(9):
    E.append((52.33 + 0.4 + o * 0.13 + 0.12, "pop", 0.16))
E += [(54.3, "sparkle", 0.14), (56.85, "whoosh", 0.3)]
E += [(57.31, "impact-bass-2", 0.5)]


def build():
    lines = []
    for n, (t, snd, vol) in enumerate(sorted(E)):
        start = max(0.0, round(t - PEAK[snd], 3))
        lines.append(f'      <audio id="sfx-{n:02d}" src="assets/sfx/{snd}.mp3" data-start="{start}" '
                     f'data-duration="{DUR[snd]}" data-track-index="{11 + n % 6}" data-volume="{vol}"></audio>')
    block = "      <!-- SFX:BEGIN generated by tools/sfx_plan.py -->\n" + "\n".join(lines) + "\n      <!-- SFX:END -->"
    p = ROOT / "index.html"
    s = p.read_text()
    if "<!-- SFX:BEGIN" in s:
        a = s.index("      <!-- SFX:BEGIN")
        b = s.index("<!-- SFX:END -->") + len("<!-- SFX:END -->")
        s = s[:a] + block + s[b:]
    else:
        s = s.replace('      <audio id="bgm"', block + '\n\n      <audio id="bgm"')
    p.write_text(s)
    print(len(lines), "sfx events")


if __name__ == "__main__":
    build()
