#!/usr/bin/env python3
"""Write the SFX layer into index.html between the SFX markers.

Each event is (visual hit time in film seconds, sound, volume). The sound's
measured peak offset is subtracted so its loudest moment lands on the hit.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PEAK = {"whoosh-short": 0.16, "whoosh": 0.16, "click": 0.07, "click-soft": 0.07, "key-press": 0.07,
        "pop": 0.11, "ping": 0.32, "impact-bass-1": 0.07, "impact-bass-2": 0.36, "sparkle": 0.02}
DUR = {"whoosh-short": 0.57, "whoosh": 0.57, "click": 0.37, "click-soft": 0.37, "key-press": 0.4,
       "pop": 0.72, "ping": 1.32, "impact-bass-1": 2.1, "impact-bass-2": 2.59, "sparkle": 1.8}

E = []
# s1: hook words, pain cards, answers
for t in [0.3, 0.42, 0.56, 0.72, 0.86, 1.06, 1.2, 1.64, 1.76, 1.92]:
    E.append((t + 0.04, "key-press", 0.16))
for i, t0 in enumerate([2.73, 4.23, 5.73, 7.23]):
    E.append((t0 + 0.06, "whoosh-short", 0.42))
    E.append((t0 + 0.52, "impact-bass-1" if i == 3 else "pop", 0.5 if i == 3 else 0.3))
# s2: wall, absorb, drop
E += [(8.8, "whoosh", 0.32), (9.4, "whoosh-short", 0.22), (10.22, "sparkle", 0.12)]
E += [(14.6, "whoosh-short", 0.22), (14.8, "whoosh-short", 0.2), (15.0, "whoosh-short", 0.2)]
E += [(16.22, "impact-bass-2", 0.55)]
E += [(19.6, "whoosh", 0.3)]
# s3: hub pop, chips, dive, pings
E.append((19.78, "pop", 0.38))
for i in range(5):
    E.append((20.23 + 0.25 * i + 0.06, "pop", 0.28))
E.append((23.12, "whoosh", 0.35))
for i in range(3):
    E.append((23.48 + 0.5 * i + 0.08, "ping", 0.3))
# s4: open, scroll, search keys, click, thread, punch
E += [(26.08, "whoosh-short", 0.28), (26.5, "whoosh", 0.25)]
for i in range(4):
    E.append((28.86 + 0.12 * i, "key-press", 0.45))
E += [(30.55, "click", 0.55), (30.8, "whoosh-short", 0.28), (32.26, "impact-bass-1", 0.42)]
# s5: open, phase morphs, verdict
E += [(34.1, "whoosh-short", 0.28)]
E += [(37.3, "whoosh-short", 0.18), (40.3, "whoosh-short", 0.18), (43.3, "whoosh-short", 0.18)]
E += [(44.79, "key-press", 0.4), (45.05, "key-press", 0.4), (45.29, "pop", 0.4)]
# s6: one click and one stamp per quadrant
for q in [46.29, 48.30, 50.32, 52.32]:
    E.append((q + 0.5, "click", 0.5))
    E.append((q + 1.02, "impact-bass-1", 0.36))
E += [(46.1, "whoosh-short", 0.25), (54.1, "whoosh-short", 0.25)]
# s7: the mark lands on the last kick
E += [(57.31, "impact-bass-2", 0.5)]


def build():
    lines = []
    for n, (t, snd, vol) in enumerate(sorted(E)):
        start = max(0.0, round(t - PEAK[snd], 3))
        lines.append(f'      <audio id="sfx-{n:02d}" src="assets/sfx/{snd}.mp3" data-start="{start}" '
                     f'data-duration="{DUR[snd]}" data-track-index="{11 + n % 6}" data-volume="{vol}"></audio>')
    block = "      <!-- SFX:BEGIN generated by tools/sfx_plan.py -->\n" + "\n".join(lines) + "\n      <!-- SFX:END -->"
    p = ROOT / "index.html"
    s = p.read_text()
    if "<!-- SFX:BEGIN" in s:
        a = s.index("      <!-- SFX:BEGIN")
        b = s.index("<!-- SFX:END -->") + len("<!-- SFX:END -->")
        s = s[:a] + block + s[b:]
    else:
        s = s.replace('      <audio id="bgm"', block + '\n\n      <audio id="bgm"')
    p.write_text(s)
    print(len(lines), "sfx events")


if __name__ == "__main__":
    build()
